Choose ans controller
LanaShhh/Voting pull request #5
Opened 2023-04-23 14:36 UTC by LanaShhh

# Что было сделано

- В тестах database -> databaseService (для одинакового названия сервиса)
- Поправила тест create poll, потому что добавила условие на число участников и ответов, а в тесте это не учла
- В databaseService tryAddById -> add, потому что лишнее обращение к базе только добавляет проблем (если нужно проверить наличие элемента в базе, это можно сделать методом get)
- Добавила remove,  если он вдруг нужен, и update
- Добавила ChooseAnswerController и примитивный тест к нему
- Добавила отдельный метод  в EmailService для отправки письма при окончании прохождения опроса всеми участниками
- Добавила в CreatePollController синхронизацию через synchronized (сейчас это не навредит но решит проблему при синхронном обращении к этому методу)

2023-04-26 01:35 UTC, 0442A403 requested changes

2023-04-26 01:35 UTC, 0442A403 commented on application/src/main/java/ru/voting/controllers/ChooseAnswerController.java
> +                    ansId = poll.getAnswers().get(i).getAnswerId();
Не нужно

2023-04-26 01:35 UTC, 0442A403 commented on application/src/main/java/ru/voting/controllers/ChooseAnswerController.java
> +            if (poll.getAnswerCounter() == poll.getAnswers().size()) {
Почему так?

2023-04-26 01:39 UTC, LanaShhh commented on application/src/main/java/ru/voting/controllers/ChooseAnswerController.java
> +            if (poll.getAnswerCounter() == poll.getAnswers().size()) {
Это похоже на баг, тут должно к во ответов сравниваться с getParticipants.size() :) утром поправлю

2023-04-26 01:41 UTC, LanaShhh commented on application/src/main/java/ru/voting/controllers/ChooseAnswerController.java
> +                    ansId = poll.getAnswers().get(i).getAnswerId();
Почему? Типо у PollAnswer есть уникальный id, и нам надо его достать. Можно через бд это сделать, но я пока решила так

2023-04-26 01:50 UTC, LanaShhh commented on application/src/main/java/ru/voting/controllers/ChooseAnswerController.java
> +                    ansId = poll.getAnswers().get(i).getAnswerId();
Все, поняла, там ansId не используется. Я уберу его

2023-05-16 07:06 UTC, 0442A403 approved these changes

2023-05-16 07:07 UTC, merged